spring:
  datasource:
    url: jdbc:mysql://121.5.79.74:3306/ordering_test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ordering_test
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  task:
    scheduling:
      timezone: Asia/Shanghai
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  mail:
      host: smtp.qq.com
      username: 3374043477@qq.com
      password: pfxkzcerlclndbje
      protocol: smtp
      port: 587

mybatis-plus:
  mapper-locations: classpath:com/blogs/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081

logging:
    level:
      root: info
      com.at.blogs.mapper: DEBUG
    file:
      path: /log
